name: Create kanji test

on:
  workflow_dispatch:
    inputs:
      n_of_kanjis:
        description: "Número de kanjis"
        required: true
        default: 250
      output_format:
        description: "Formato de salida"
        required: true
        default: "csv"

jobs:
  create_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          path: tools

      - name: Checkout kanjis repo
        uses: actions/checkout@v4
        with:
          repository: eoi-japones/kanji-data
          ref: main
          path: kanji-data

      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Create test
        run: |
          ls -lha
          cd tools/kanji_tests && cargo run -- -n ${{ github.event.inputs.n_of_kanjis }} -o ${{ github.event.inputs.output_format }} "../../kanji-data/data" >> kanji_test.csv

      - name: Save to repo 
        run: |
          cd tools/kanji_tests
          git config --global user.name "Kanji tests"
          git config --global user.email "tests@users.noreply.github.com"
          git add kanji_test.csv
          git commit -m "Kanji test created"
          git push



